/* Auto-generated by src/scripts/extract-file-icons.mjs — do not edit by hand. */
import type { IconifyIcon } from "@iconify/types";

export const ICON_WIDTH = 32 as const;
export const ICON_HEIGHT = 32 as const;

export const FILE_ICON_DATA = {
  "angular": {
    "body": "<g fill=\"none\" fill-rule=\"evenodd\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#ed8796\" d=\"m8 1l6.5 2l-1 9.5L8 15l-5.5-2.5l-1-9.5z\"/><path stroke=\"#cad3f5\" d=\"m4.5 10.5l3.5-7l3.5 7m-5.796-2h4.635\"/></g>"
  },
  "apache": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#ed8796\" d=\"M2.5 14.5a24.3 24.3 0 0 1 1.63-4.36c.21-.42.45-.84.7-1.26c2.75-4.61 6.63-6.8 8.67-7.38c-.8 3.52-3.91 10.46-10.15 10.4\"/><path stroke=\"#f5a97f\" d=\"M6.14 6.96C8.7 3.64 11.76 1.99 13.5 1.5a18.5 18.5 0 0 1-2.27 5.46\"/><path stroke=\"#ed8796\" d=\"M6.5 9.5h-2m1.25-2h2.71\"/></g>"
  },
  "astro-config": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"M8.591 8.591c-.466-.204-.932-.371-1.35-.445l-1.798-4.95l-1.797 4.95C2.649 8.32 1.398 9.022.5 9.488l2.843-7.992c.109-.357.163-.536.27-.669A.9.9 0 0 1 3.97.563C4.13.5 4.315.5 4.69.5h1.709c.374 0 .561 0 .72.064a.9.9 0 0 1 .355.263c.107.133.162.312.271.67L9.729 7.5\"/><path stroke=\"#c6a0f6\" d=\"M6.561 11.145a5 5 0 0 1-1.003.1c-1.094 0-2.01-.336-2.254-.79c-.087.26-.106.558-.106.748c0 0-.058.933.598 1.582c0-.337.276-.61.616-.61c.583 0 .582.503.582.912v.037c0 .62.383 1.152.928 1.376a1.24 1.24 0 0 1-.127-.548c0-.592.35-.812.759-1.068\"/><path stroke=\"#8087a2\" d=\"M11.5 13.5a1 1 0 1 0 0-2a1 1 0 0 0 0 2m1.752-4l1.75 3l-1.75 3h-3.5l-1.75-3l1.75-3z\"/></g>"
  },
  "babel": {
    "body": "<path fill=\"none\" stroke=\"#eed49f\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M3.42 4.02c1.1-.68 2.32-1.53 3.63-1.95c1.16-.38 2.43-.73 3.62-.5c.6.13 1.27.41 1.57.93c.3.5.3 1.18.05 1.68c-.97 1.88-5.26 3.6-5.26 3.6m1.2-5.92L2.47 14.5s6.14-2.13 8.23-4.43c.44-.48.96-1.17.75-1.78c-.18-.53-.9-.75-1.45-.85c-1.56-.26-4.67.92-4.67.92\"/>"
  },
  "bash": {
    "body": "<g fill=\"none\" stroke=\"#a6da95\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2 15.5c-.7 0-1.5-.8-1.5-1.5V5c0-.7.8-1.5 1.5-1.5h9c.7 0 1.5.8 1.5 1.5v9c0 .7-.8 1.5-1.5 1.5z\"/><path d=\"m1.2 3.8l3.04-2.5S5.17.5 5.7.5h8.4c.66 0 1.4.73 1.4 1.4v7.73a2.7 2.7 0 0 1-.7 1.75l-2.68 3.51\"/><path d=\"M6 8.75c0-.69-.54-1.25-1.2-1.25h-.6c-.66 0-1.2.56-1.2 1.25S3.54 10 4.2 10h.6c.66 0 1.2.56 1.2 1.25s-.54 1.25-1.2 1.25h-.6c-.66 0-1.2-.56-1.2-1.25M4.5 6.5v1m0 5v1\"/></g>"
  },
  "batch": {
    "body": "<g fill=\"none\" stroke=\"#8aadf4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2 15.5c-.7 0-1.5-.8-1.5-1.5V5c0-.7.8-1.5 1.5-1.5h9c.7 0 1.5.8 1.5 1.5v9c0 .7-.8 1.5-1.5 1.5z\"/><path d=\"m1.2 3.8l3.04-2.5S5.17.5 5.7.5h8.4c.66 0 1.4.73 1.4 1.4v7.73a2.7 2.7 0 0 1-.7 1.75l-2.68 3.51M3 8.5l3 2l-3 2\"/></g>"
  },
  "bun-lock": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#8087a2\" d=\"M15 11.51c.28 0 .5.23.5.5v3a.5.5 0 0 1-.5.5h-5a.5.5 0 0 1-.5-.5v-3c0-.27.22-.5.5-.5zm-4 0v-1.5a1.5 1.5 0 1 1 3 0v1.5\"/><path stroke=\"#f4dbd6\" d=\"M14.5 7.01c0-3.69-4.2-5.57-7-6.5c-2.8.93-7 2.81-7 6.5c0 4.85 5.13 5.5 7 5.5\"/><path stroke=\"#ee99a0\" d=\"M5.5 8.51h4c-.67.67-1.33 1-2 1s-1.33-.33-2-1\"/><path stroke=\"#cad3f5\" d=\"M5 6.51a.5.5 0 1 0 0-1a.5.5 0 0 0 0 1m5 0a.5.5 0 1 0 0-1a.5.5 0 0 0 0 1\"/></g>"
  },
  "c": {
    "body": "<path fill=\"none\" stroke=\"#8aadf4\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4.056 12.952a7.05 7.05 0 0 0 9.944 0l-1.79-1.783a4.513 4.513 0 0 1-6.364 0a4.47 4.47 0 0 1 0-6.338a4.513 4.513 0 0 1 6.364 0l.895-.891l.895-.892a7.05 7.05 0 0 0-9.944 0a6.98 6.98 0 0 0 0 9.904\" clip-rule=\"evenodd\"/>"
  },
  "cargo": {
    "body": "<g fill=\"none\" fill-rule=\"evenodd\" stroke=\"#f5a97f\" stroke-linejoin=\"round\"><path stroke-linecap=\"round\" d=\"M1.5 7L8 10.5L14.5 7m-10-2.5l3.503 2L14.498 3M4.5 5.5v7m3.5-6V14\"/><path stroke-linecap=\"round\" d=\"M8.003 3L11.5 4.5v8\"/><path stroke-linecap=\"square\" d=\"M1.5 6.984V11l6.503 3.5L14.5 11V3L11 1.5l-6.5 3v1z\"/></g>"
  },
  "cmake": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#a6da95\" d=\"m6 11.5l-3.5 3H13Z\"/><path stroke=\"#ed8796\" d=\"m9 1.5l5.5 11l-4.5-2z\"/><path stroke=\"#8aadf4\" d=\"m1.5 12.5l6-5l-.5-6Z\"/></g>"
  },
  "cpp": {
    "body": "<path fill=\"none\" stroke=\"#8aadf4\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M2.556 12.952a7.05 7.05 0 0 0 9.944 0l-1.79-1.783a4.513 4.513 0 0 1-6.364 0a4.47 4.47 0 0 1 0-6.338a4.513 4.513 0 0 1 6.364 0l.895-.891l.895-.892a7.05 7.05 0 0 0-9.944 0a6.98 6.98 0 0 0 0 9.904\" clip-rule=\"evenodd\"/><path fill=\"none\" stroke=\"#8aadf4\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M7.5 6v4M5.514 8h3.999m3.973-2v4M11.5 8h4\"/>"
  },
  "csharp": {
    "body": "<path fill=\"none\" stroke=\"#8aadf4\" d=\"M6.666 1.01a1 1 0 0 1 .822 1.15L7.18 3.999h2.972l.36-2.165a1 1 0 0 1 1.971.328l-.303 1.837H14a.999.999 0 1 1 0 2h-2.153l-.666 4H13a.999.999 0 1 1 0 2h-2.153l-.36 2.166a1 1 0 0 1-1.971-.328l.306-1.834H5.847l-.36 2.165a1 1 0 0 1-1.971-.328L3.819 12H2a.999.999 0 1 1 0-2h2.153l.666-4H3a.999.999 0 1 1 0-2h2.153l.36-2.166a1 1 0 0 1 1.15-.822Zm.18 4.988l-.665 4h2.972l.666-4Z\"/>"
  },
  "css": {
    "body": "<g fill=\"none\" stroke=\"#c6a0f6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 1.5h8A2.5 2.5 0 0 1 14.5 4v8a2.5 2.5 0 0 1-2.5 2.5H4A2.5 2.5 0 0 1 1.5 12V4A2.5 2.5 0 0 1 4 1.5\"/><path stroke-width=\".814\" d=\"M10.24 11.53c0 .58.438 1.038.96 1.035l.453-.004c.522-.003.949-.451.949-1.033c0-.58-.427-1.065-.95-1.065h-.451c-.523 0-.95-.486-.95-1.066s.427-1.038.95-1.038h.452c.522 0 .951.458.951 1.039M6.8 11.529c0 .58.438 1.04.96 1.036l.465-.004c.523-.003.936-.451.936-1.031s-.409-1.066-.931-1.066h-.47c-.522 0-.949-.485-.949-1.066c0-.58.427-1.037.95-1.037h.451c.523 0 .964.457.964 1.037M3.407 11.53c0 .58.438 1.052.96 1.052h.452c.522 0 .95-.457.95-1.038m.01-2.131c0-.58-.437-1.038-.96-1.038h-.451c-.523 0-.96.468-.96 1.05v2.118\"/></g>"
  },
  "cypress": {
    "body": "<g fill=\"none\" stroke=\"#a6da95\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M7.5 9.393c-.476.873-1.446 1.308-2.376 1.065S3.532 9.353 3.501 8.347s.578-1.91 1.491-2.216c.913-.305 1.908.064 2.436.903m3.072 2.968L8.5 6m-.503 8.5c.367-.048.527-.073.731-.21c.126-.106.245-.28.302-.433L12.5 6\"/><path d=\"M7.964 14.5a6.5 6.5 0 1 1 3.838-1.228\"/></g>"
  },
  "database": {
    "body": "<path fill=\"none\" stroke=\"#eed49f\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M8 6.5c3.59 0 6.5-1.4 6.5-2.68S11.59 1.5 8 1.5S1.5 2.54 1.5 3.82S4.41 6.5 8 6.5M14.5 8c0 .83-1.24 1.79-3.25 2.2s-4.49.41-6.5 0S1.5 8.83 1.5 8m13 4.18c0 .83-1.24 1.6-3.25 2c-2.01.42-4.49.42-6.5 0c-2.01-.4-3.25-1.17-3.25-2m0-8.3v8.3m13-8.3v8.3\"/>"
  },
  "docker": {
    "body": "<path fill=\"none\" stroke=\"#8aadf4\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M.5 8.5H11l.75-.5a5.35 5.35 0 0 1 0-3.5c1 .6 1 1.88 1.74 2c.77-.09 1.23.01 2 .52c0 0-.97 1.77-2.5 1.98c-1.93 3.65-4.5 5.5-6.98 5.5C0 14.5.5 8.5.5 8.5m1 0v-2m0 0h8m-6 2v-4m0 0h4m-2-2h2m-2 6v-6m2 6v-6m2 6v-2\"/>"
  },
  "docker-compose": {
    "body": "<path fill=\"none\" stroke=\"#8bd5ca\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M.5 8.5H11l.75-.5a5.35 5.35 0 0 1 0-3.5c1 .6 1 1.88 1.74 2c.77-.09 1.23.01 2 .52c0 0-.97 1.77-2.5 1.98c-1.93 3.65-4.5 5.5-6.98 5.5C0 14.5.5 8.5.5 8.5m1 0v-2m0 0h8m-6 2v-4m0 0h4m-2-2h2m-2 6v-6m2 6v-6m2 6v-2\"/>"
  },
  "editorconfig": {
    "body": "<path fill=\"none\" stroke=\"#f4dbd6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M3.86 6.46c.23.08.46.15.66.28a2 2 0 0 1 .66.6c.1.15.17.35.15.53a.8.8 0 0 1-.29.53c-.2.16-.5.14-.74.15a3.9 3.9 0 0 1-1.5-.32a3.5 3.5 0 0 1-.64-.31c-.18-.12-.44-.25-.55-.45A.73.73 0 0 1 1.5 7c.02-.18.1-.4.24-.51c.18-.16.49-.2.72-.23a4.3 4.3 0 0 1 1.4.2m4.05 1.7c.23.05.47.1.7.17c.24.08.5.15.72.3c.17.13.38.27.45.48c.05.15.02.65-.05.8a.97.97 0 0 1-.37.39a1.4 1.4 0 0 1-.6.2c-.18.03-.37-.03-.56-.05c-.25-.04-.5-.07-.73-.13c-.27-.07-.56-.13-.8-.28c-.17-.1-.32-.24-.43-.4a.9.9 0 0 1-.11-.33a2.8 2.8 0 0 1 0-.74c.03-.1.1-.2.19-.27c.1-.1.23-.18.37-.21c.19-.06.39-.03.58-.02c.22.02.43.06.64.1zM3.59 6.04s.3-.61.52-.85a4.1 4.1 0 0 1 3.17-.97a4.25 4.25 0 0 1 2 .7c.24.18.47.4.67.64a5.4 5.4 0 0 1 1.04 2.02c.08.34.12.7.1 1.06a5.3 5.3 0 0 1-.56 1.86c-.11.21-.25.4-.39.6a7.3 7.3 0 0 1-2.29 2.17c-.5.3-1.04.53-1.58.73c-.53.2-1.06.4-1.62.47c-.4.05-.81.06-1.2-.02a2.6 2.6 0 0 1-.98-.43a2.7 2.7 0 0 1-.8-1.08a2.9 2.9 0 0 1-.17-1.04c0-.16 0-.32.02-.47c.02-.2.03-.4.07-.6a9 9 0 0 1 .95-2.34m2.49-4c-.02-.19-.06-.37-.06-.56c0-.22.02-.45.07-.66c.04-.13.1-.25.16-.37c.08-.15.17-.3.28-.42c.12-.15.27-.26.42-.38c.12-.1.23-.2.37-.27a2.6 2.6 0 0 1 1.02-.32c.13 0 .26 0 .39.02a1.08 1.08 0 0 1 .62.41c.09.12.17.25.2.4c.02.09.01.2 0 .3c-.02.19-.06.38-.13.57c-.04.1-.1.21-.16.31c-.12.22-.27.42-.4.62m3.07 2.45s.33-.5.55-.67c.2-.17.43-.3.68-.37c.36-.09.75-.1 1.1-.01a1.66 1.66 0 0 1 1.2 1.22a1.88 1.88 0 0 1-.11 1.42c-.19.33-.5.57-.79.8a3 3 0 0 1-1.6.72c-.23.04-.71.02-.71.02\"/>"
  },
  "env": {
    "body": "<path fill=\"none\" stroke=\"#eed49f\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M5.5 8.5V12m0-6.5V4m0 4.5a1.5 1.5 0 1 0 0-3a1.5 1.5 0 0 0 0 3m5 3.5v-1.5m0-3V4m0 6.5a1.5 1.5 0 1 0 0-3a1.5 1.5 0 0 0 0 3M4 1.5h8A2.5 2.5 0 0 1 14.5 4v8a2.5 2.5 0 0 1-2.5 2.5H4A2.5 2.5 0 0 1 1.5 12V4A2.5 2.5 0 0 1 4 1.5\"/>"
  },
  "eslint": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#c6a0f6\" d=\"M11.71 1.5L15.42 8l-3.71 6.5H4.29L.58 8l3.71-6.5z\"/><path stroke=\"#b7bdf8\" d=\"m8 4.07l3.5 1.97v3.92L8 11.93L4.5 9.96V6.04z\"/></g>"
  },
  "file": {
    "body": "<path fill=\"none\" stroke=\"#cad3f5\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M13.5 6.5v6a2 2 0 0 1-2 2h-7a2 2 0 0 1-2-2v-9c0-1.1.9-2 2-2h4.01m-.01 0l5 5h-4a1 1 0 0 1-1-1z\"/>"
  },
  "folder": {
    "body": "<path fill=\"none\" stroke=\"#cad3f5\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4.5 4.5H12c.83 0 1.5.67 1.5 1.5v6c0 .83-.67 1.5-1.5 1.5H2A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/>"
  },
  "folder-assets": {
    "body": "<path fill=\"none\" stroke=\"#cad3f5\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4.5 4.5H12c.83 0 1.5.67 1.5 1.5v.5m-7.5 7H2A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path fill=\"none\" stroke=\"#eed49f\" stroke-linejoin=\"round\" d=\"M12.923 11.904H7.5L10.212 7Z\"/><path fill=\"none\" stroke=\"#eed49f\" stroke-linejoin=\"round\" d=\"M11.662 9.641a2.569 2.596 0 1 1-1.308 2.263\"/>"
  },
  "folder-assets-open": {
    "body": "<path fill=\"none\" stroke=\"#cad3f5\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"m1.87 8l.7-2.74a1 1 0 0 1 .96-.76h10.94a1 1 0 0 1 .97 1.24L15.12 7M6 13.5H2A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path fill=\"none\" stroke=\"#eed49f\" stroke-linejoin=\"round\" d=\"M12.923 11.904H7.5L10.21 7Z\"/><path fill=\"none\" stroke=\"#eed49f\" stroke-linejoin=\"round\" d=\"M11.662 9.641a2.569 2.596 0 1 1-1.308 2.263\"/>"
  },
  "folder-components": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"M4.5 4.5H12c.83 0 1.5.67 1.5 1.5v.5m-7.5 7H2A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#a6da95\" d=\"m9.485 9.516l3.968 3.968m-3.968 0l3.968-3.968m-1.634-1.874l3.507 3.507a.496.496 0 0 1 0 .702l-3.507 3.507a.496.496 0 0 1-.701 0L7.61 11.85a.496.496 0 0 1 0-.702l3.507-3.507a.496.496 0 0 1 .701 0z\"/></g>"
  },
  "folder-components-open": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"m1.87 8l.7-2.74a1 1 0 0 1 .96-.76h10.94a1 1 0 0 1 .97 1.24l-.219.875M6 13.5H2A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#a6da95\" d=\"m9.485 9.516l3.968 3.968m-3.968 0l3.968-3.968m-1.634-1.874l3.507 3.507a.496.496 0 0 1 0 .702l-3.507 3.507a.496.496 0 0 1-.701 0L7.61 11.85a.496.496 0 0 1 0-.702l3.507-3.507a.496.496 0 0 1 .701 0z\"/></g>"
  },
  "folder-config": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"M4.5 4.5H12c.83 0 1.5.67 1.5 1.5v.5m-7.5 7H2A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#8087a2\" d=\"M11.498 13a1 1 0 1 0 0-2a1 1 0 0 0 0 2m1.752-4L15 12l-1.75 3h-3.5L8 12l1.75-3z\"/></g>"
  },
  "folder-config-open": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"m1.87 8l.7-2.74a1 1 0 0 1 .96-.76h10.94a1 1 0 0 1 .97 1.24l-.219.875M6 13.5H2A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#8087a2\" d=\"M11.498 13a1 1 0 1 0 0-2a1 1 0 0 0 0 2m1.752-4L15 12l-1.75 3h-3.5L8 12l1.75-3z\"/></g>"
  },
  "folder-dist": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"M4.5 4.5H12A1.5 1.5 0 0 1 13.5 6v.5m-7.5 7H2A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#ed8796\" d=\"M9.5 10.5h5a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1v-3a1 1 0 0 1 1-1m1-2h3v2h-3z\"/></g>"
  },
  "folder-dist-open": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"m1.875 8l.686-2.743a1 1 0 0 1 .97-.757h10.938a1 1 0 0 1 .97 1.243l-.315 1.26M6 13.5H2.004A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#ed8796\" d=\"M9.5 10.5h5a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1v-3a1 1 0 0 1 1-1m1-2h3v2h-3z\"/></g>"
  },
  "folder-docs": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"M4.5 4.5H12A1.5 1.5 0 0 1 13.5 6v.5m-7.5 7H2A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#8aadf4\" d=\"M8.5 14.5v-5a1 1 0 0 1 1-1h6v6m-6-1h6v2h-6a1 1 0 1 1 0-2\"/></g>"
  },
  "folder-docs-open": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"m1.875 8l.686-2.743a1 1 0 0 1 .97-.757h10.938a1 1 0 0 1 .97 1.243l-.315 1.26M6 13.5H2.004A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#8aadf4\" d=\"M8.5 14.5v-5a1 1 0 0 1 1-1h6v6m-6-1h6v2h-6a1 1 0 1 1 0-2\"/></g>"
  },
  "folder-git": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"M4.5 4.5H12A1.5 1.5 0 0 1 13.5 6v.5m-7.5 7H2A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#f5a97f\" d=\"M10.5 10.5v3m-.75-4.75L8 7m4.75 4.75l-1.5-1.5m-.75 5.25a1 1 0 1 0 0-2a1 1 0 0 0 0 2m0-5a1 1 0 1 0 0-2a1 1 0 0 0 0 2m3 3a1 1 0 1 0 0-2a1 1 0 0 0 0 2\"/></g>"
  },
  "folder-git-open": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"m1.875 8l.686-2.743a1 1 0 0 1 .97-.757h10.938a1 1 0 0 1 .97 1.243l-.315 1.26M6 13.5H2.004A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#f5a97f\" d=\"M10.5 10.5v3m-.75-4.75L8 7m4.75 4.75l-1.5-1.5m-.75 5.25a1 1 0 1 0 0-2a1 1 0 0 0 0 2m0-5a1 1 0 1 0 0-2a1 1 0 0 0 0 2m3 3a1 1 0 1 0 0-2a1 1 0 0 0 0 2\"/></g>"
  },
  "folder-node": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"M4.5 4.5H12A1.5 1.5 0 0 1 13.5 6v.5m-7.5 7H2A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#a6da95\" d=\"m12.5 8.576l3 1.714v3.42l-3 1.714l-3-1.714v-3.42z\"/></g>"
  },
  "folder-node-open": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"m1.875 8l.686-2.743a1 1 0 0 1 .97-.757h10.938a1 1 0 0 1 .97 1.243l-.315 1.26M6 13.5H2.004A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#a6da95\" d=\"m12.5 8.576l3 1.714v3.42l-3 1.714l-3-1.714v-3.42z\"/></g>"
  },
  "folder-open": {
    "body": "<path fill=\"none\" stroke=\"#cad3f5\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"m1.87 8l.7-2.74a1 1 0 0 1 .96-.76h10.94a1 1 0 0 1 .97 1.24l-1.75 7a1 1 0 0 1-.97.76H2A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/>"
  },
  "folder-public": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"M4.5 4.5H12A1.5 1.5 0 0 1 13.5 6v.5m-7.5 7H2A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#7dc4e4\" d=\"M8.5 12h7M12 15.5c-1.933 0-3.5-1.5-3.5-3.5s1.567-3.5 3.5-3.5c2 0 3.5 1.5 3.5 3.5S14 15.5 12 15.5M11.556 9c-1.379 2.01-1.448 4.01.087 6.34M12.454 9c1.361 1.98 1.45 3.98-.062 6.34\"/></g>"
  },
  "folder-public-open": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"m1.875 8l.686-2.743a1 1 0 0 1 .97-.757h10.938a1 1 0 0 1 .97 1.243l-.315 1.26M6 13.5H2.004A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#7dc4e4\" d=\"M8.5 12h7M12 15.5c-1.933 0-3.5-1.5-3.5-3.5s1.567-3.5 3.5-3.5c2 0 3.5 1.5 3.5 3.5S14 15.5 12 15.5M11.556 9c-1.38 2.01-1.448 4.01.087 6.34M12.454 9c1.36 1.98 1.45 3.98-.062 6.34\"/></g>"
  },
  "folder-scripts": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"M4.5 4.5H12A1.5 1.5 0 0 1 13.5 6v.5m-7.5 7H2A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#c6a0f6\" d=\"M8.5 13.5V9.75C8.5 9 9 8.5 9.75 8.5h3.75v5.75c0 .75-.5 1.25-1.25 1.25H8.5a1 1 0 0 1 0-2h3a1 1 0 0 0 0 2m2-5h1a1 1 0 0 0 0-2h-1\"/></g>"
  },
  "folder-scripts-open": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"m1.875 8l.686-2.743a1 1 0 0 1 .97-.757h10.938a1 1 0 0 1 .97 1.243l-.315 1.26M6 13.5H2.004A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#c6a0f6\" d=\"M8.5 13.5V9.75C8.5 9 9 8.5 9.75 8.5h3.75v5.75c0 .75-.5 1.25-1.25 1.25H8.5a1 1 0 0 1 0-2h3a1 1 0 0 0 0 2m2-5h1a1 1 0 0 0 0-2h-1\"/></g>"
  },
  "folder-src": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"M4.5 4.5H12A1.5 1.5 0 0 1 13.5 6v.5m-7.5 7H2A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#a6da95\" d=\"m10.5 8.5l-3 3.5l3 3.5m2-7l3 3.5l-3 3.5\"/></g>"
  },
  "folder-src-open": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"m1.875 8l.686-2.743a1 1 0 0 1 .97-.757h10.938a1 1 0 0 1 .97 1.243l-.315 1.26M6 13.5H2.004A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#a6da95\" d=\"m10.5 8.5l-3 3.5l3 3.5m2-7l3 3.5l-3 3.5\"/></g>"
  },
  "folder-tests": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"M4.5 4.5H12A1.5 1.5 0 0 1 13.5 6v.5m-7.5 7H2A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#8bd5ca\" d=\"m13.158 9.16l-4.272 4.254c-.558.555-.45 1.31-.064 1.694c.406.403 1.077.64 1.743-.023l4.269-4.25M12.5 8.501l.5.5l1 1l1 1l.5.5m-3.478 2.005H8.96\"/></g>"
  },
  "folder-tests-open": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"m1.875 8l.686-2.743a1 1 0 0 1 .97-.757h10.938a1 1 0 0 1 .97 1.243l-.315 1.26M6 13.5H2.004A1.5 1.5 0 0 1 .5 12V3.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1\"/><path stroke=\"#8bd5ca\" d=\"m13.158 9.16l-4.272 4.253c-.558.555-.45 1.31-.064 1.694c.406.404 1.077.641 1.743-.022l4.269-4.25M12.5 8.5l.5.5l1 1l1 1l.5.5m-3.478 2.006H8.96\"/></g>"
  },
  "git": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"M8.5 10.5a1 1 0 0 1-1 1a1 1 0 0 1-1-1a1 1 0 0 1 1-1a1 1 0 0 1 1 1m0-6a1 1 0 0 1-1 1a1 1 0 0 1-1-1a1 1 0 0 1 1-1a1 1 0 0 1 1 1m3 3a1 1 0 0 1-1 1a1 1 0 0 1-1-1a1 1 0 0 1 1-1a1 1 0 0 1 1 1m-4-2v4m-1-6l-1-1m4 4l-1-1\"/><path stroke=\"#f5a97f\" d=\"m9.06 1.06l5.88 5.88a1.5 1.5 0 0 1 0 2.12l-5.88 5.88a1.5 1.5 0 0 1-2.12 0L1.06 9.06a1.5 1.5 0 0 1 0-2.12l5.88-5.88a1.5 1.5 0 0 1 2.12 0\"/></g>"
  },
  "go": {
    "body": "<path fill=\"none\" stroke=\"#7dc4e4\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"m15.48 8.06l-4.85.48m4.85-.48a4.98 4.98 0 0 1-4.54 5.42a5 5 0 1 1 2.95-8.66l-1.7 1.84a2.5 2.5 0 0 0-4.18 2.06c.05.57.3 1.1.69 1.51c.25.27 1 .83 1.78.82c.8-.02 1.58-.25 2.07-.81c0 0 .8-.96.68-1.88M2.5 8.5l-2 .01m1.5 2h1.5m-2-3.99l2-.02\"/>"
  },
  "go-mod": {
    "body": "<path fill=\"none\" stroke=\"#7dc4e4\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"m2.5 8.51l-2 .01m1.5 2h1.5m-2-4h1m6.73-2.19a1.5 1.5 0 1 0-2.16.58m2.16-.58l2.78-.74l.75 2.78m.57 2.16l.75 2.79l-7.73 2.07l-2.07-7.73l2.78-.75m6.28 3.63a1.5 1.5 0 1 0-.58-2.17\"/>"
  },
  "gradle": {
    "body": "<g fill=\"none\" stroke=\"#7dc4e4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m7.5 7.5l-1.97.78c-.2.15-.74.33-1.2-.2a7.3 7.3 0 0 1-1-1.63\"/><path d=\"M11.43 2.98c.54-.48 4.07-1.39 4.07 2.1c0 2.34-1.6 3.53-2.76 4.5c-.75.61-1.35 1.28-1.35 3.92H9.88c0-1.29-2.66-2.32-3.17 0H5.38c0-1.29-2.65-2.32-3.16 0H.7C.29 11.92.22 8.3 3.33 6.45c-.15-.25-.27-1.02.43-1.3c.87-.34 3.77-1.34 6.51.12s5.01 1.12 5.14.74\"/></g>"
  },
  "html": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#f5a97f\" d=\"M1.5 1.5h13L13 13l-5 2l-5-2z\"/><path stroke=\"#cad3f5\" d=\"M11 4.5H5l.25 3h5.5l-.25 3l-2.5 1l-2.5-1l-.08-1\"/></g>"
  },
  "image": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#eed49f\" d=\"M11.5 6A1.5 1.5 0 0 1 10 7.5A1.5 1.5 0 0 1 8.5 6A1.5 1.5 0 0 1 10 4.5A1.5 1.5 0 0 1 11.5 6\"/><path stroke=\"#a6da95\" d=\"M7.5 13.5L11 10c.5-.5 1.5-.5 2 0l1.5 1.5\"/><path stroke=\"#a6da95\" d=\"m1.5 9.5l2-2C4 7 5 7 5.5 7.5l4 4\"/><path stroke=\"#7dc4e4\" d=\"M3 2.5h10c.83 0 1.5.67 1.5 1.5v8c0 .83-.67 1.5-1.5 1.5H3A1.5 1.5 0 0 1 1.5 12V4c0-.83.67-1.5 1.5-1.5\"/></g>"
  },
  "java": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"M10.73 8.41c.57 3 1.59 5.83 2.77 7.09c-6.63-3.45-9.76-1.75-10.5 0c-.66-3.4-.54-5.74.09-7.78\"/><path stroke=\"#ed8796\" d=\"M8.5 7c.63.34 1.82 1.07 2.24 1.41c-.54-2.9-.64-5.96-.74-7.91c-2.13.58-5.73 1.98-6.9 7.22c.52-.69 1.72-1.05 2.4-1.22\"/><path stroke=\"#ed8796\" d=\"M5.5 7A1.5 1.5 0 0 0 7 8.5A1.5 1.5 0 0 0 8.5 7A1.5 1.5 0 0 0 7 5.5A1.5 1.5 0 0 0 5.5 7\"/></g>"
  },
  "javascript": {
    "body": "<g fill=\"none\" stroke=\"#eed49f\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4.5 11a1.5 1.5 0 0 0 3 0V7.5m5 1.25c0-.69-.537-1.25-1.2-1.25h-.6c-.663 0-1.2.56-1.2 1.25S10.037 10 10.7 10h.6c.663 0 1.2.56 1.2 1.25s-.537 1.25-1.2 1.25h-.6c-.663 0-1.2-.56-1.2-1.25\"/><path d=\"M4 1.5h8c1.385 0 2.5 1.115 2.5 2.5v8c0 1.385-1.115 2.5-2.5 2.5H4A2.495 2.495 0 0 1 1.5 12V4c0-1.385 1.115-2.5 2.5-2.5\"/></g>"
  },
  "javascript-config": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#eed49f\" d=\"M9.5 5c-.33-.33-.83-.5-1.5-.5c-1 0-1.5.5-1.5 1s.5 1 1.5 1s1.5.5 1.5 1s-.5 1-1.5 1c-.67 0-1.17-.17-1.5-.5m-2-3.5v3a1 1 0 1 1-2 0\"/><path stroke=\"#eed49f\" d=\"M6.5 11.5h-4a2 2 0 0 1-2-2v-7c0-1.1.9-2 2-2h7a2 2 0 0 1 2 2V7\"/><path stroke=\"#8087a2\" d=\"M11.5 13.5a1 1 0 1 0 0-2a1 1 0 0 0 0 2m1.75-4l1.75 3l-1.75 3h-3.5L8 12.5l1.75-3z\"/></g>"
  },
  "javascript-react": {
    "body": "<g fill=\"none\" stroke=\"#91d7e3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 10.8c4.14 0 7.5-1.25 7.5-2.8S12.14 5.2 8 5.2S.5 6.45.5 8s3.36 2.8 7.5 2.8\"/><path d=\"M5.52 9.4c2.07 3.5 4.86 5.72 6.23 4.95c1.37-.78.8-4.24-1.27-7.75C8.41 3.1 5.62.88 4.25 1.65c-1.37.78-.8 4.24 1.27 7.75\"/><path d=\"M5.52 6.6c-2.07 3.5-2.64 6.97-1.27 7.75c1.37.77 4.16-1.45 6.23-4.95s2.64-6.97 1.27-7.75C10.38.88 7.59 3.1 5.52 6.6\"/><path d=\"M8.5 8a.5.5 0 0 1-.5.5a.5.5 0 0 1-.5-.5a.5.5 0 0 1 .5-.5a.5.5 0 0 1 .5.5\"/></g>"
  },
  "jest": {
    "body": "<g fill=\"none\" stroke=\"#ed8796\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M7.5 6L5.56 1.5h9.94l-2 4.5\"/><path d=\"m12.5 6l-2-2.5l-2 2.5m1 1.5h2m2 1.5c1 1-.5 2.75-3 4s-4.5 1.5-6 1.5c-2 0-3-1-3-2.9q0-1.35 1.5-2.1\"/><path d=\"M7.5 9c0 1.5-2 2.5-3 2.5S3 11.25 3 9.5\"/><path d=\"M4.5 8.5a1 1 0 0 1-1 1a1 1 0 0 1-1-1a1 1 0 0 1 1-1a1 1 0 0 1 1 1m5-1A1.5 1.5 0 0 1 8 9a1.5 1.5 0 0 1-1.5-1.5A1.5 1.5 0 0 1 8 6a1.5 1.5 0 0 1 1.5 1.5m5 0A1.5 1.5 0 0 1 13 9a1.5 1.5 0 0 1-1.5-1.5A1.5 1.5 0 0 1 13 6a1.5 1.5 0 0 1 1.5 1.5\"/></g>"
  },
  "json": {
    "body": "<path fill=\"none\" stroke=\"#eed49f\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4.5 2.5H4c-.75 0-1.5.75-1.5 1.5v2c0 1.1-1 2-1.83 2c.83 0 1.83.9 1.83 2v2c0 .75.75 1.5 1.5 1.5h.5m7-11h.5c.75 0 1.5.75 1.5 1.5v2c0 1.1 1 2 1.83 2c-.83 0-1.83.9-1.83 2v2c0 .74-.75 1.5-1.5 1.5h-.5m-6.5-3a.5.5 0 1 0 0-1a.5.5 0 0 0 0 1m3 0a.5.5 0 1 0 0-1a.5.5 0 0 0 0 1m3 0a.5.5 0 1 0 0-1a.5.5 0 0 0 0 1\"/>"
  },
  "kotlin": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#c6a0f6\" d=\"M2.5 13.5h11L8 8\"/><path stroke=\"#f5a97f\" d=\"M8.03 2.5h5.47l-8 8\"/><path stroke=\"#ed8796\" d=\"M2.5 13.5V8\"/><path stroke=\"#7dc4e4\" d=\"M8 2.5H2.5V8l3-2.5\"/></g>"
  },
  "license": {
    "body": "<path fill=\"none\" stroke=\"#f5a97f\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4.5 13.5h7M8.01 1v12.06M1.5 3.5h3l1.5-1h4l1.5 1h3M.5 10L3 4.48L5.5 10C4 11 2 11 .5 10m10 0L13 4.48L15.5 10c-1.5 1-3.5 1-5 0\"/>"
  },
  "lua": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#cad3f5\" d=\"M10.5 7A1.5 1.5 0 0 1 9 8.5A1.5 1.5 0 0 1 7.5 7A1.5 1.5 0 0 1 9 5.5A1.5 1.5 0 0 1 10.5 7\"/><path stroke=\"#8aadf4\" d=\"M7 2.5a6.5 6.5 0 1 0 0 13a6.5 6.5 0 0 0 0-13m7-2a1.5 1.5 0 1 0 0 3a1.5 1.5 0 0 0 0-3\"/></g>"
  },
  "makefile": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#f5a97f\" d=\"m9.24 8.47l-5.28 5.58c-.56.6-1.47.6-2.04 0a1.57 1.57 0 0 1 0-2.14L7.2 6.32\"/><path stroke=\"#cad3f5\" d=\"m13.74 8.03l-.86-.93a2.46 2.46 0 0 1-.64-1.68v-.65l-1.89-2.04A3.7 3.7 0 0 0 7.63 1.5H5.5l.64.61A4.72 4.72 0 0 1 7.5 5.57v1.16l1.46 1.5h1.71l1.57 1.42m-.74.85l3-3\"/></g>"
  },
  "markdown": {
    "body": "<path fill=\"none\" stroke=\"#7dc4e4\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"m9.25 8.25l2.25 2.25l2.25-2.25M3.5 11V5.5l2.04 3l1.96-3V11m4-.5V5M1.65 2.5h12.7c.59 0 1.15.49 1.15 1v9c0 .51-.56 1-1.15 1H1.65c-.59 0-1.15-.49-1.15-1V3.58c0-.5.56-1.08 1.15-1.08\"/>"
  },
  "markdown-mdx": {
    "body": "<path fill=\"none\" stroke=\"#f5a97f\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"m9.25 8.25l2.25 2.25l2.25-2.25M3.5 11V5.5l2.04 3l1.96-3V11m4-.5V5M1.65 2.5h12.7c.59 0 1.15.49 1.15 1v9c0 .51-.56 1-1.15 1H1.65c-.59 0-1.15-.49-1.15-1V3.58c0-.5.56-1.08 1.15-1.08\"/>"
  },
  "next": {
    "body": "<g fill=\"none\" stroke=\"#cad3f5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12.33 12.85a6.5 6.5 0 1 1 1.55-2.08\"/><path d=\"M12.33 12.85L5.5 4.5v7m5-7v3\"/></g>"
  },
  "npm-lock": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#8087a2\" d=\"M15 11.5c.27 0 .5.22.5.5v3a.5.5 0 0 1-.5.5h-5a.5.5 0 0 1-.5-.5v-3c0-.28.22-.5.5-.5zm-4 0V10a1.5 1.5 0 0 1 3 0v1.5\"/><path stroke=\"#cad3f5\" d=\"M9.5 9V5.5h-2v6h-4v-8h8v3\"/><path stroke=\"#ed8796\" d=\"M7.54 13.5H3A1.5 1.5 0 0 1 1.5 12V3c0-.83.67-1.5 1.5-1.5h9c.83 0 1.5.67 1.5 1.5v3.5\"/></g>"
  },
  "nuxt": {
    "body": "<path fill=\"none\" stroke=\"#a6da95\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M9.5 12.5h6l-5-7L7.44 11c-.67.98-1.32 1.48-1.94 1.5h-5l5-9l3 5\"/>"
  },
  "package-json": {
    "body": "<path fill=\"none\" stroke=\"#a6da95\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M11.5 6.5v-.17c0-.73-.6-1.33-1.33-1.33H9a1.5 1.5 0 1 0 0 3h1a1.5 1.5 0 0 1 0 3H9a1.5 1.5 0 0 1-1.5-1.5M5.5 5v4.5c0 1.5-.08 1.87-.71 2.5c-.5.5-1.5.5-1.5.5c-.96-.4-1.2-.66-1.79-1v-7L8 .5l6.5 4v7l-6.5 4l-2.49-1.53\"/>"
  },
  "php": {
    "body": "<path fill=\"none\" stroke=\"#8aadf4\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M.5 12.5v.74c0 .76.774 1.26 1.5 1.26c.938 0 1.5-.5 1.5-1.255V6c0-1.715 1.494-3.478 3.65-3.501c2.344 0 3.85 1.558 3.85 3c.166 2.99-1.422 4.137-3.504 5v4h8.002V9c.041-.635-.56-1.844-1.367-2.5c-.937-.692-2.073-.997-3.131-1m.5 9v-3M6 6.5a.5.5 0 1 0 0-1a.5.5 0 0 0 0 1\"/>"
  },
  "playwright": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#ed8796\" d=\"M5 9.5c-1.02.35-1.5 1-1.5 1\"/><path stroke=\"#ed8796\" d=\"m5.97 12.36l-.1.03c-2.98.8-4.55-2.64-5.03-4.43C.62 7.13.53 6.28.5 5.88c-.03-.46.29-.33.89-.23a6.5 6.5 0 0 0 2.7-.17c.52-.14 1.26-.4 1.74-.65\"/><path stroke=\"#ed8796\" d=\"M2.5 7.5s.36.56 1.18.31C4.5 7.57 4.5 7 4.5 7\"/><path stroke=\"#a6da95\" d=\"M15.05 7.57c-.62 2.33-2.67 6.81-6.52 5.78C4.68 12.3 5.14 7.4 5.77 5.08c.28-1.07.58-1.84.81-2.31c.27-.54.53-.18 1.14.32a8.4 8.4 0 0 0 3.14 1.56a8.4 8.4 0 0 0 3.49.22c.78-.13 1.19-.3 1.15.29c-.04.52-.16 1.33-.45 2.4Z\"/><path stroke=\"#a6da95\" d=\"M9.5 7.5s0-.82-.72-1.08s-1.28.08-1.28.08m0 3S8 11 9.21 11.33c1.21.34 2.29-.83 2.29-.83M13 9s.18-.87-.58-1.23C11.66 7.4 11 8 11 8\"/></g>"
  },
  "pnpm-lock": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#8087a2\" d=\"M15 11.5c.27 0 .5.22.5.5v3a.5.5 0 0 1-.5.5h-5a.5.5 0 0 1-.5-.5v-3c0-.28.22-.5.5-.5zm-4 0V10a1.5 1.5 0 0 1 3 0v1.5\"/><path stroke=\"#f5a97f\" d=\"M4.5 1.5v3\"/><path stroke=\"#cad3f5\" d=\"M7.5 7.5v3m-3-6v6\"/><path stroke=\"#f5a97f\" d=\"M7.5 1.5v6m3 0v-6h-9v3h9\"/><path stroke=\"#cad3f5\" d=\"M10.5 7.5h-9v3h7\"/></g>"
  },
  "powershell": {
    "body": "<g fill=\"none\" stroke=\"#8aadf4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2 15.5c-.7 0-1.5-.8-1.5-1.5V5c0-.7.8-1.5 1.5-1.5h9c.7 0 1.5.8 1.5 1.5v9c0 .7-.8 1.5-1.5 1.5z\"/><path d=\"m1.2 3.8l3.04-2.5S5.17.5 5.7.5h8.4c.66 0 1.4.73 1.4 1.4v7.73a2.7 2.7 0 0 1-.7 1.75l-2.68 3.51M3 8.5l3 2l-3 2m4 0h2\"/></g>"
  },
  "prettier": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#7dc4e4\" d=\"M1.5 2.5h11m-11 6h5\"/><path stroke=\"#eed49f\" d=\"M1.5 4.5h5m3 4h5\"/><path stroke=\"#c6a0f6\" d=\"M9.5 4.5h5m-13 2h5m-5 6h5\"/><path stroke=\"#ed8796\" d=\"M9.5 6.5h5m-13 4h11m-11 4h5\"/></g>"
  },
  "prisma": {
    "body": "<path fill=\"none\" stroke=\"#8bd5ca\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"m8 .5l6.5 12.05l-10 2.95l-3-5zm-3.5 15L8 .5\"/>"
  },
  "python": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#8aadf4\" d=\"M8.5 5.5h-3m6 0V3c0-.8-.7-1.5-1.5-1.5H7c-.8 0-1.5.7-1.5 1.5v2.5H3c-.8 0-1.5.7-1.5 1.5v2c0 .8.7 1.5 1.48 1.5\"/><path stroke=\"#eed49f\" d=\"M10.5 10.5h-3m-3 0V13c0 .8.7 1.5 1.5 1.5h3c.8 0 1.5-.7 1.5-1.5v-2.5H13c.8 0 1.5-.7 1.5-1.5V7c0-.8-.7-1.5-1.48-1.5H11.5c0 1.5 0 2-1 2h-2\"/><path stroke=\"#8aadf4\" d=\"M2.98 10.5H4.5c0-1.5 0-2 1-2h2m0-5\"/></g>"
  },
  "python-config": {
    "body": "<path fill=\"none\" stroke=\"#8087a2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M11.5 13.5a1 1 0 1 0 0-2a1 1 0 0 0 0 2m1.75-4l1.75 3l-1.75 3h-3.5L8 12.5l1.75-3z\"/><g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#8aadf4\" d=\"M6.961 4.192h-2.77m5.54 0V1.884C9.73 1.146 9.083.5 8.345.5h-2.77c-.738 0-1.384.646-1.384 1.384v2.308H1.884C1.146 4.192.5 4.838.5 5.577v1.846c0 .738.646 1.384 1.366 1.384\"/><path stroke=\"#eed49f\" d=\"M8.115 8.807H6.038m-2.77 0v2.308c0 .739.647 1.385 1.385 1.385h1.385m6.35-4.55c.071-.164.112-.343.112-.527V5.577c0-.739-.646-1.385-1.366-1.385H9.73c0 1.385 0 1.846-.923 1.846H6.961\"/><path stroke=\"#8aadf4\" d=\"M1.866 8.807h1.403c0-1.384 0-1.846.923-1.846h1.846m0-4.615\"/></g>"
  },
  "readme": {
    "body": "<g fill=\"none\" stroke=\"#8bd5ca\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 14.5a6.5 6.5 0 1 0 0-13a6.5 6.5 0 0 0 0 13\"/><path d=\"M7 7.5h2v5H7Zm2-3a1 1 0 0 1-1 1a1 1 0 0 1-1-1a1 1 0 0 1 1-1a1 1 0 0 1 1 1\"/></g>"
  },
  "rollup": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#ed8796\" d=\"M4.37 14.5h9.13l-2-5c1.36-1.08 2-2.13 2-4c0-2.4-2.25-3.97-4-4h-7v11.3\"/><path stroke=\"#eed49f\" d=\"M11.46 6.2c-3.25 3.32-4.37 4.25-7.2 8.3c-1.03-.13-1.67-.61-1.74-1.55c-.36-.35 4.87-8.22 5.42-9.16c.6-1 2.55-2.22 3.78-1.4c-1.18-.38-2.58.56-2.41 1.5l.47 1.89c.34.58.66.8 1.18.73c.56-.16.67-.53.63-1l-.36-.99\"/></g>"
  },
  "ruby": {
    "body": "<path fill=\"none\" stroke=\"#ed8796\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M1.5 9.06v2.5c.02.86.36 1.61.9 2.15c1.76 1.76 5.71.65 8.84-2.47c3.12-3.13 4.23-7.08 2.47-8.84a3.1 3.1 0 0 0-2.15-.9h-2.5M14.5 4l-.25 10.25L4 14.5m4.39-6.11c2.34-2.35 3.29-5.2 2.12-6.37S6.49 1.8 4.14 4.14C1.8 6.5.85 9.34 2.02 10.51s4.02.22 6.37-2.12M5.5 14.5l.25-3.75L11 11l-.25-5.25l3.75-.25\"/>"
  },
  "ruby-gem": {
    "body": "<g fill=\"none\" stroke=\"#ed8796\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m8 12.5l4.5-5l-2-2h-5l-2 2z\"/><path d=\"M14.5 12L8 15.5L1.5 12V4L8 .5L14.5 4z\"/></g>"
  },
  "rust": {
    "body": "<g fill=\"none\" stroke=\"#f5a97f\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15.5 9.5Q8 13.505.5 9.5l1-1l-1-2l2-.5V4.5h2l.5-2l1.5 1l1.5-2l1.5 2l1.5-1l.5 2h2V6l2 .5l-1 2z\"/><path d=\"M6.5 7.5a1 1 0 0 1-1 1a1 1 0 0 1-1-1a1 1 0 0 1 1-1a1 1 0 0 1 1 1m5 0a1 1 0 0 1-1 1a1 1 0 0 1-1-1a1 1 0 0 1 1-1a1 1 0 0 1 1 1M4 11.02c-.67.37-1.5.98-1.5 2.23s1.22 1.22 2 1.25v-2M12 11c.67.37 1.5 1 1.5 2.25s-1.22 1.22-2 1.25v-2\"/></g>"
  },
  "sass": {
    "body": "<path fill=\"none\" stroke=\"#f5bde6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M6.75 6.38c1.85 1.07 3.35.74 4.83-.2c1.5-.95 2.7-2.78 1.3-4.15c-.7-.68-3.25-.8-5.62.19c-2.36.99-4.59 3.02-4.74 4.11c-.31 2.19 3.15 2.88 3.64 4.23s.28 1.98-.2 2.83c-.5.85-1.96 1.62-2.8.68c-.83-.95 1.67-2.75 2.98-3.25c1.3-.5 3.1-.4 3.69.25c.58.64-.07 1.79-.03 1.79\"/>"
  },
  "svelte": {
    "body": "<g fill=\"none\" stroke=\"#f5a97f\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12.86 6.72s1.39-1.98.08-3.87C11.286.763 9.44 1.6 9.44 1.6S6.15 3.35 4.33 4.59c-1.4 1-2.24 2.26-1.03 4.37c1.22 2.1 4.58 1.21 4.58 1.21\"/><path d=\"M3.14 9.28s-1.39 1.98-.08 3.87c1.31 1.9 3.5 1.24 3.5 1.24s3.29-1.74 5.11-2.98c1.4-1 2.24-2.26 1.03-4.37c-1.22-2.1-4.58-1.21-4.58-1.21M6.3 6.96l4.14-2.56m-4.92 7.25L9.66 9.1\"/></g>"
  },
  "svg": {
    "body": "<path fill=\"none\" stroke=\"#f5a97f\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"m4.54 10l6.92-4m-6.92 4a1.5 1.5 0 1 0-2.6 1.5a1.5 1.5 0 0 0 2.6-1.5M8 4v8m0-8a1.5 1.5 0 1 0 0-3a1.5 1.5 0 0 0 0 3M4.54 6l6.92 4M4.54 6a1.5 1.5 0 1 0-2.6-1.5A1.5 1.5 0 0 0 4.54 6M8 12a1.5 1.5 0 1 0 0 3a1.5 1.5 0 0 0 0-3m3.46-2a1.5 1.5 0 1 0 2.6 1.5a1.5 1.5 0 0 0-2.6-1.5m0-4a1.5 1.5 0 1 0 2.6-1.5a1.5 1.5 0 0 0-2.6 1.5\"/>"
  },
  "swift": {
    "body": "<path fill=\"none\" stroke=\"#f5a97f\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M14.34 10.2c.34-1.08 1.1-5.07-4.45-8.62a.48.48 0 0 0-.6.07a.44.44 0 0 0-.02.6c.03.02 2.07 2.5 1.34 5.34c-1.26-.86-6.24-4.81-6.24-4.81L7.25 7.5L1.9 4.05S5.68 8.7 8 10.45c-1.12.4-3.56.82-6.78-1.18a.48.48 0 0 0-.58.06a.44.44 0 0 0-.08.56c.11.18 2.7 4.36 8.14 4.36c1.5 0 2.37-.42 3.08-.77c.43-.2.77-.37 1.14-.37c.93 0 1.54.92 1.54.93c.1.14.27.22.44.21a.46.46 0 0 0 .4-.28c.67-1.55-.49-3.2-.96-3.78h0Z\"/>"
  },
  "tailwind": {
    "body": "<path fill=\"none\" stroke=\"#7dc4e4\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M8 2.5q-3 0-3.75 3.33C5 4.73 5.88 4.31 6.87 4.58c.58.16.98.62 1.43 1.13c.74.83 1.6 1.79 3.45 1.79q3 0 3.75-3.33c-.75 1.1-1.63 1.52-2.63 1.25c-.57-.16-.97-.62-1.42-1.13C10.7 3.46 9.85 2.5 8 2.5m-3.75 6q-3 0-3.75 3.33c.75-1.1 1.63-1.52 2.63-1.25c.57.16.97.62 1.42 1.13c.74.83 1.6 1.79 3.45 1.79q3 0 3.75-3.33c-.75 1.1-1.63 1.52-2.62 1.25c-.58-.16-.98-.62-1.43-1.13c-.74-.83-1.6-1.79-3.45-1.79\"/>"
  },
  "tauri": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#eed49f\" d=\"M4.73 4.02a4.64 4.64 0 1 1 5.55 6.56\"/><path stroke=\"#91d7e3\" d=\"M7.5 10a.5.5 0 0 1-.5.5a.5.5 0 0 1-.5-.5a.5.5 0 0 1 .5-.5a.5.5 0 0 1 .5.5\"/><path stroke=\"#91d7e3\" d=\"M11.26 12a4.64 4.64 0 1 1-5.63-6.55\"/><path stroke=\"#eed49f\" d=\"M9.5 6a.5.5 0 0 1-.5.5a.5.5 0 0 1-.5-.5a.5.5 0 0 1 .5-.5a.5.5 0 0 1 .5.5\"/></g>"
  },
  "toml": {
    "body": "<path fill=\"none\" stroke=\"#ee99a0\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M3.5 1.5h-2v13h2m9-13h2v13h-2m-8-11h7v3h-2v6h-3v-6h-2z\"/>"
  },
  "typescript": {
    "body": "<g fill=\"none\" stroke=\"#8aadf4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 1.5h8A2.5 2.5 0 0 1 14.5 4v8a2.5 2.5 0 0 1-2.5 2.5H4A2.5 2.5 0 0 1 1.5 12V4A2.5 2.5 0 0 1 4 1.5\"/><path d=\"M12.5 8.75c0-.69-.54-1.25-1.2-1.25h-.6c-.66 0-1.2.56-1.2 1.25S10.04 10 10.7 10h.6c.66 0 1.2.56 1.2 1.25s-.54 1.25-1.2 1.25h-.6c-.66 0-1.2-.56-1.2-1.25m-3-3.75v5M5 7.5h3\"/></g>"
  },
  "typescript-config": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#8087a2\" d=\"M11.5 13.5a1 1 0 1 0 0-2a1 1 0 0 0 0 2m1.75-4l1.75 3l-1.75 3h-3.5L8 12.5l1.75-3z\"/><path stroke=\"#8aadf4\" d=\"M6.5 11.5h-4a2 2 0 0 1-2-2v-7c0-1.1.9-2 2-2h7.97c1.1 0 2 .92 2 2V7\"/><path stroke=\"#8aadf4\" d=\"M10.5 4.5C10.17 4.17 9.67 4 9 4c-1 0-1.5.5-1.5 1S8 6 9 6s1.5.5 1.5 1S10 8 9 8c-.67 0-1.17-.17-1.5-.5M4 4v4M2.5 4h3\"/></g>"
  },
  "typescript-react": {
    "body": "<g fill=\"none\" stroke=\"#8aadf4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 11.3c4.14 0 7.5-1.28 7.5-2.86S12.14 5.58 8 5.58S.5 6.86.5 8.44s3.36 2.87 7.5 2.87Z\"/><path d=\"M5.52 9.87c2.07 3.6 4.86 5.86 6.23 5.07c1.37-.8.8-4.34-1.27-7.93S5.62 1.16 4.25 1.95s-.8 4.34 1.27 7.92\"/><path d=\"M5.52 7.01c-2.07 3.59-2.64 7.14-1.27 7.93s4.16-1.48 6.23-5.07c2.07-3.58 2.64-7.13 1.27-7.92c-1.37-.8-4.16 1.47-6.23 5.06\"/><path d=\"M8.5 8.44a.5.5 0 0 1-.5.5a.5.5 0 0 1-.5-.5a.5.5 0 0 1 .5-.5a.5.5 0 0 1 .5.5\"/></g>"
  },
  "vite": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#c6a0f6\" d=\"m11 5.5l3.5-1l-6.5 11l-6.5-11l3.5 1\"/><path stroke=\"#eed49f\" d=\"m6 1.5l-.5 5l2-1l-1 3L8 8v3l4-7.5l-2 .5L11.5.5Z\"/></g>"
  },
  "vitest": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#a6da95\" d=\"m14.5 8.5l-6.5 6l-6.5-6\"/><path stroke=\"#eed49f\" d=\"M7.5 11.5L8 8L5 7l4.5-5.5L9 5l3 1z\"/></g>"
  },
  "vue": {
    "body": "<g fill=\"none\" stroke=\"#a6da95\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M1 1.5h5.44L8 4.56L9.56 1.5H15l-6.99 13z\"/><path d=\"M12.05 1.73L8 9.28L3.95 1.73\"/></g>"
  },
  "web-assembly": {
    "body": "<g fill=\"none\" stroke=\"#c6a0f6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m9.5 12.5l1.5-4l1.5 4m-2.5-1h2m-8.5-3l1 4l1.5-4l1.5 4l1-4\"/><path d=\"M10.5 1.5h2a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-9a2 2 0 0 1-2-2v-9c0-1.1.9-2 2-2h2v0\"/><path d=\"M5.5 1.5c0 1.38.5 3 2.5 3s2.5-1.62 2.5-3\"/></g>"
  },
  "webpack": {
    "body": "<g fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path stroke=\"#91d7e3\" d=\"m4.5 10.02l-3 1.73M11.47 10l3.03 1.75M8 4V.5\"/><path stroke=\"#8aadf4\" d=\"M11.5 10L8 12l-3.5-2V6L8 4l3.5 2z\"/><path stroke=\"#91d7e3\" d=\"M14.5 11.75L8 15.5l-6.5-3.75v-7.5L8 .5l6.5 3.75zm-13-7.5L8 8m6.5-3.75L8 8m0 0v7.5\"/></g>"
  },
  "xml": {
    "body": "<path fill=\"none\" stroke=\"#f5a97f\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4.5 4.5L1 8l3.5 3.5m7-7L15 8l-3.5 3.5M9.5 2l-3 12\"/>"
  },
  "yaml": {
    "body": "<path fill=\"none\" stroke=\"#ed8796\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M2.5 1.5h3l3 4l3-4h3l-9 13h-3L7 8z\"/>"
  },
  "yarn-lock": {
    "body": "<path fill=\"none\" stroke=\"#8087a2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M15 11.5c.27 0 .5.22.5.5v3a.5.5 0 0 1-.5.5h-5a.5.5 0 0 1-.5-.5v-3c0-.28.22-.5.5-.5zm-4 0V10a1.5 1.5 0 0 1 3 0v1.5\"/><g fill=\"none\" stroke=\"#c6a0f6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"7.179\"><path d=\"M58.19 92.889c-2.438 1.472-16.058 7.342-33.033.927c0 0-15.323 4.247-14.195-6.503c0 0-10.684-12.422.938-22.28c0 0-1.241-16.91 11.549-24.936c0 0-8.286-12.228 0-19.036s12.645-9.145 18.736-8.634c0 0 7.247-20.251 14.643 0c0 0 9.061-7.776 7.844 17.247c-.323 6.646-4.717 16.289-7.844 20.326c0 0 2.22 1.58 4.44 5.612c1.11 2.015 2.22 4.643 3.053 7.992a45 45 0 0 1 1.006 5.578\" transform=\"matrix(.13927 0 0 .13933 -.413 .02)\"/><path d=\"M27.469 94.285c-1.525-1.407.321-8.703.321-8.703s-1.252 4.723-3.116 7.525\" transform=\"matrix(.13927 0 0 .13933 -.413 .02)\"/></g>"
  },
  "zip": {
    "body": "<path fill=\"none\" stroke=\"#cad3f5\" stroke-linejoin=\"round\" d=\"M5.5 10v1m1-2v1m-1-2v1m1-2v1m-1-2v1m1-2v1m-1-2v1m0-3v1m1 0v1m7 2.5v6a2 2 0 0 1-2 2h-7a2 2 0 0 1-2-2v-9c0-1.1.9-2 2-2h4.01m-.01 0l5 5h-4a1 1 0 0 1-1-1z\"/>"
  }
} as const satisfies Record<
  string,
  Pick<IconifyIcon, "body" | "width" | "height">
>;
